export const SAVE_LEFT_CODE = 'SAVE_LEFT_CODE';

export const WRITE_CODE = 'WRITE_CODE';

export const LOSER = 'LOSER';

export const POPULATE_RIGHT_DESCRIPTION = 'POPULATE_RIGHT_DESCRIPTION';

export const SUBMIT_CODE = 'SUBMIT_CODE';

export const PASSED_TESTS = 'PASSED_TESTS';

export const FAILED_TESTS = 'FAILED_TESTS';

export const SOCKET_DESCRIPTION = 'SOCKET_DESCRIPTION';

export const SAVE_ROOM_ID = 'SAVE_ROOM_ID';

export const JOIN_ROOM = 'JOIN_ROOM';

export const JOINED = 'JOINED';

export const TEST_RETURNED = 'TEST_RETURNED';

export const TEST_FAILED = 'TEST_FAILED';

export const GOT_CHALLENGE = 'GOT_CHALLENGES';

export const GET_CHALLENGE_ERROR = 'GET_CHALLENGE_ERROR';
